version: '3.8'

services:
  app:
    build: .
    container_name: mithril-app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    expose:
      - "80"
    ports:
      - "8080:80"  # Optional: For local access at localhost:8080
    networks:
      - mithril-net

  backend:
    build:
      context: ./backend
    container_name: mithril-backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ABUSEIPDB_KEY=${ABUSEIPDB_KEY}
    volumes:
      - ./backend/forge_stats.json:/app/forge_stats.json
    networks:
      - mithril-net

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mithril-tunnel
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - mithril-net
    depends_on:
      - app

networks:
  mithril-net:
    driver: bridge
